### ISSUE TITLE
貌似支付功能不能用哦，有没有人用起来的

### ISSUE THREAD

**Issue by ax3353** [ThierrySquirrel/alipay#1]

**Comment by ThierrySquirrel** [comment]
您好,有什么可以帮助您的？

**Comment by ax3353** [comment]
关于app2.0支付  我看官方文档要求的是AlipayTradeAppPayResponse response = alipayClient.sdkExecute(request);  此处client执行请求的时候需要调用sdkExecute这个方法，而您调用的execute方法，因此支付网关一直提示验证签名失败，我换用sdkExecute方法后就可以通过，我猜测是此处引起的吧

**Comment by ThierrySquirrel** [comment]
的确如此，对于疏忽深感抱歉，将迅速修复此处问题，十分感谢您对项目的帮助.

**Comment by ax3353** [comment]
您太客气啦，感谢您的付出

**Comment by ThierrySquirrel** [comment]
新的版本已经更新，最晚17.30之后，将可以使用新的版本，再次感谢您的帮助.
